### PR TITLE
add support for rpi3

### PR DESCRIPTION
**Pull request by yangxuan8282**

### CODE REVIEW

**Comment by cecton** [comment]
I think the author doesn't care about arm and wants to keep the packet confusing for arm users #5

**Comment by helixarch** [comment]
I do care about ARM, I just don't have an ARM device to test it

**Comment by cecton** [comment]
This PR breaks the compatibility with i386 and x86_64: http://ports.ubuntu.com/ubuntu-ports/dists/xenial/

**Comment by guatedude2** [comment]
Yeah, I tested the PR, there is no official arm version of ubuntu. 

Alejandro Gonzalez

**Pull request closed without merging**
